---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: &app database
spec:
  interval: 60m
  chart:
    spec:
      chart: pgadmin4
      version: 1.24.1
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  values:
    image:
      repository: dpage/pgadmin4
      tag: "7.8"
    strategy:
      type: Recreate
    env:
      email: ${SECRET_ACME_EMAIL}
    #   password: ${SECRET_PGADMIN_PASSWORD}
    existingSecret: pgadmin-secret
    secretKeys:
      pgadminPasswordKey: password
    ingress:
      enabled: true
      ingressClassName: "internal"
      hosts:
        - host: pgadmin.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix

      tls:
        - secretName: pgadmin-tls
          hosts:
            - pgadmin.${SECRET_DOMAIN}

    persistentVolume:
      enabled: true
      existingClaim: pgadmin-config-v1
