---

name: Schedule - Update Flux

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * *'

jobs:
  flux-upgrade:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        fetch-depth: 1

    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main

    - name: Upgrade Flux
      id: upgrade
      run: |
        CLI_VERSION="$(flux -v)"
        VERSION="v${CLI_VERSION#*flux version }"
        flux install --version="${VERSION}" \
          --network-policy=false \
          --export > ./cluster/base/flux-system/gotk-components.yaml
        echo "::set-output name=flux_version::$VERSION"

    - name: Create pull request for Flux upgrade
      uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: "flux/upgrade-${{ steps.upgrade.outputs.flux_version }}"
        delete-branch: true
        title: "chore(deps): upgrade flux components to ${{ steps.upgrade.outputs.flux_version }}"
        signoff: true
        committer: "dkw99 <dkw99@users.noreply.github.com>"
        author: "dkw99 <dkw99@users.noreply.github.com>"
        assignees: "dkw99"
        commit-message: "chore(deps): upgrade flux components to ${{ steps.upgrade.outputs.flux_version }}"
        body: |
          Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.upgrade.outputs.flux_version }}
        labels: flux/upgrade
